spring:
  application:
    name: inventory-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:7000/saga-choreography
    username: root
    password: sibi@soft
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
server:
  port: 7101